# Generated by Django 3.2.9 on 2022-01-13 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField(verbose_name='tổng tiền')),
                ('paid_status', models.BooleanField(default=False, verbose_name='trạng thái thanh toán')),
                ('order_dt', models.CharField(default=datetime.datetime(2022, 1, 13, 14, 28, 2, 433085), max_length=50, verbose_name='ngày đặt hàng')),
                ('order_status', models.CharField(choices=[('Confirmed', 'Đã được xác nhận '), ('sender ready', 'người gửi chuẩn bị hàng '), ('order has been delivered', 'đơn hàng đã được bàn giao cho đơn vị vận chuyển'), ('shipping', ' đang giao hàng'), ('delivered', 'đã giao hàng')], default='process', max_length=150, verbose_name='tình trạng đơn hàng')),
                ('complete', models.BooleanField(default=False, verbose_name='hoàn thành')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='thuộc tài khoản ')),
            ],
            options={
                'verbose_name_plural': '5.Đơn Hàng',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='tên danh mục')),
            ],
            options={
                'verbose_name_plural': '2.danh mục sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='categoryblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tên chủ đề')),
            ],
            options={
                'verbose_name_plural': '8.chủ đề bài viết',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='địa chỉ')),
                ('lastname', models.CharField(max_length=200, verbose_name='tên người nhận')),
                ('phone', models.CharField(max_length=200, verbose_name='số điện thoại')),
                ('des', models.CharField(max_length=200, verbose_name='mô tả')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('date_added', models.CharField(default=datetime.datetime(2022, 1, 13, 14, 28, 2, 433085), max_length=50, verbose_name='thời gian đặt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cartorder', verbose_name='địa chỉ thuộc tài khoản')),
            ],
            options={
                'verbose_name_plural': '7.địa chỉ giao hàng',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(max_length=100, verbose_name='tên sản phẩm')),
                ('description', models.TextField(verbose_name='mô tả')),
                ('img', models.ImageField(upload_to='image/', verbose_name='ảnh sản phẩm')),
                ('price', models.FloatField(default=0.0, verbose_name='giá')),
                ('status', models.BooleanField(default=True, verbose_name='trạng thái')),
                ('slug', models.IntegerField(verbose_name='số lượng')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('trái', 'trái'), ('giỏ', 'giỏ trái cây')], default='kg', max_length=10, verbose_name='đơn tính')),
                ('is_feature', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='danh mục')),
            ],
            options={
                'verbose_name_plural': '3.sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='DProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='image/details/', verbose_name='chi tiết ảnh')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products', verbose_name='thuộc sản phẩm')),
            ],
            options={
                'verbose_name_plural': '4. chi tiết ảnh sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_field', models.CharField(max_length=15, verbose_name='số điện thoại')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tài khoản')),
            ],
            options={
                'verbose_name_plural': '1.khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=150, verbose_name='mã hóa đơn')),
                ('item', models.CharField(max_length=150, verbose_name='tên sản phẩm')),
                ('image', models.CharField(max_length=200, verbose_name='ảnh sản phẩm')),
                ('qty', models.IntegerField(verbose_name='số lượng')),
                ('price', models.FloatField(verbose_name='giá')),
                ('total', models.FloatField(verbose_name='tổng tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cartorder', verbose_name='đơn hàng')),
            ],
            options={
                'verbose_name_plural': '6.Chi Tiết Đơn Đặt Hàng',
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tên bài viết')),
                ('description', models.TextField(verbose_name='mô tả')),
                ('image', models.ImageField(upload_to='image/blog', verbose_name='ảnh bài viết')),
                ('status', models.BooleanField(default=True, verbose_name='trạng thái')),
                ('date_at', models.CharField(default=datetime.datetime(2022, 1, 13, 14, 28, 2, 433085), max_length=50, verbose_name='ngày đăng')),
                ('cateblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryblog', verbose_name='thuộc chủ đề')),
            ],
            options={
                'verbose_name_plural': '9.chi tiết bài viết',
            },
        ),
    ]
