# Generated by Django 3.2.9 on 2022-01-13 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tên người phản hồi')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('message', models.TextField(verbose_name='lời nhắn')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 14, 46, 10, 749081), max_length=50, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 14, 46, 10, 749081), max_length=50, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 14, 46, 10, 749081), max_length=50, verbose_name='thời gian đặt'),
        ),
    ]
