# Generated by Django 3.2.9 on 2022-01-13 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220113_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '10.phản hồi'},
        ),
        migrations.AddField(
            model_name='contact',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 2, 23, 489770), editable=False, max_length=50, verbose_name='ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 2, 23, 489770), editable=False, max_length=50, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 2, 23, 489770), editable=False, max_length=50, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 2, 23, 489770), editable=False, max_length=50, verbose_name='thời gian đặt'),
        ),
    ]
