# Generated by Django 3.2.9 on 2022-01-13 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220113_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '09.chi tiết bài viết'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '05.Đơn Hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '06.Chi Tiết Đơn Đặt Hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '02.danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='categoryblog',
            options={'verbose_name_plural': '08.chủ đề bài viết'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '01.khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='dproducts',
            options={'verbose_name_plural': '04. chi tiết ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': '03.sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': '07.địa chỉ giao hàng'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 19, 15, 487062), editable=False, max_length=50, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 19, 15, 487062), editable=False, max_length=50, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 19, 15, 487062), editable=False, max_length=50, verbose_name='ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='giá'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 15, 19, 15, 487062), editable=False, max_length=50, verbose_name='thời gian đặt'),
        ),
    ]
