# Generated by Django 3.2.9 on 2022-01-14 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220113_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 14, 13, 39, 24, 636834), editable=False, max_length=50, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.CharField(default=datetime.datetime(2022, 1, 14, 13, 39, 24, 636834), editable=False, max_length=50, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Confirmed', 'Đã được xác nhận '), ('sender ready', 'người gửi chuẩn bị hàng '), ('order has been delivered', 'đơn hàng đã được bàn giao cho đơn vị vận chuyển'), ('shipping', ' đang giao hàng'), ('delivered', 'đã giao hàng')], default='Confirmed', max_length=150, verbose_name='tình trạng đơn hàng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 14, 13, 39, 24, 636834), editable=False, max_length=50, verbose_name='ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.CharField(default=datetime.datetime(2022, 1, 14, 13, 39, 24, 636834), editable=False, max_length=50, verbose_name='thời gian đặt'),
        ),
    ]
