# Generated by Django 3.2.9 on 2022-01-16 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220114_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 16, 14, 4, 7, 79498), editable=False, max_length=50, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.CharField(default=datetime.datetime(2022, 1, 16, 14, 4, 7, 79498), editable=False, max_length=50, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 16, 14, 4, 7, 79498), editable=False, max_length=50, verbose_name='ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=9999, verbose_name='giá'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.IntegerField(default=9999, verbose_name='số lượng'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.CharField(default=datetime.datetime(2022, 1, 16, 14, 4, 7, 79498), editable=False, max_length=50, verbose_name='thời gian đặt'),
        ),
    ]
