# Generated by Django 3.2.9 on 2022-01-16 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220117_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_at',
            field=models.CharField(default=datetime.datetime(2022, 1, 17, 0, 27, 17, 176074), editable=False, max_length=50, verbose_name='ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='thời gian đặt'),
        ),
    ]
