# Generated by Django 3.2.9 on 2022-01-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_blog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='exit', verbose_name='mô tả ngắn'),
            preserve_default=False,
        ),
    ]
